[workspace]
members = [
    "crates/*",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.86.0"
license = "AGPL-3.0"

[workspace.dependencies]
radroots-runtime = { path = "../../crates/crates/runtime" }

anyhow = { version = "1" }
clap = { version = "4" }
jsonrpsee = { version = "0.26" }
nostr = { version = "0.43.0", features = ["nip04"] }
nostr-sdk = { version = "0.43.0" }
serde = { version = "1", default-features = false }
serde_json = { version = "1", default-features = false }
tokio = { version = "1" }
thiserror = { version = "1" }
tracing = { version = "0.1" }
