[package]
name = "radrootsd"
version = "0.1.0"
edition = "2024"
authors = ["triesap npub1tr33s4tj2le2kk9yzhfphdtss26gyn8kv7savnnjhj794nqp333q8e7grr"]
rust-version = "1.88.0"
license = "AGPL-3.0"
description = "Radroots daemon binary"

[workspace]
resolver = "2"

[workspace.dependencies]
radroots-core = { path = "../../../../vendor/radroots/rs/crates/core" }
radroots-events = { path = "../../../../vendor/radroots/rs/crates/events" }
radroots-events-codec = { path = "../../../../vendor/radroots/rs/crates/events-codec" }
radroots-identity = { path = "../../../../vendor/radroots/rs/crates/identity" }
radroots-nostr = { path = "../../../../vendor/radroots/rs/crates/nostr" }
radroots-runtime = { path = "../../../../vendor/radroots/rs/crates/runtime" }
radroots-trade = { path = "../../../../vendor/radroots/rs/crates/trade" }

[dependencies]
radroots-core = { workspace = true, features = ["std", "serde", "typeshare"]  }
radroots-events = { workspace = true, features = ["serde"] }
radroots-events-codec = { workspace = true, features = ["nostr", "serde_json"] }
radroots-identity = { workspace = true }
radroots-nostr = { workspace = true, features = ["client", "codec", "events", "http"] }
radroots-runtime = { workspace = true, features = ["cli"] }
radroots-trade = { workspace = true }
nostr = { version = "0.44.2", features = ["nip46"] }

anyhow = { version = "1" }
clap = { version = "4", features = ["derive"] }
jsonrpsee = { version = "0.26", features = ["server"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = { version = "1", default-features = false }
serde_qs = { version = "0.12" }
tokio = { version = "1", features = ["full"] }
thiserror = { version = "1" }
tracing = { version = "0.1" }
uuid = { version = "1.16.0", features = ["v4"] }
url = { version = "2.5.4" }
